#!/usr/bin/env python
import os
import sys
import json
from subprocess import CalledProcessError, DEVNULL, check_output


def resolve_branch_name():
    try:
        return check_output(
            ['git', 'symbolic-ref', '--short', 'HEAD'],
            stderr=DEVNULL,
        ).strip().decode('UTF-8')
    except CalledProcessError:
        pass

    for rebase_meta in ('.git/rebase-merge/head-name', '.git/rebase-apply/head-name'):
        if os.path.isfile(rebase_meta):
            with open(rebase_meta, 'r', encoding='utf8') as fh:
                head_name = fh.read().strip()
            if head_name.startswith('refs/heads/'):
                return head_name[len('refs/heads/'):]
            return head_name

    try:
        branch = check_output(
            ['git', 'branch', '--show-current'],
            stderr=DEVNULL,
        ).strip().decode('UTF-8')
        if branch:
            return branch
    except CalledProcessError:
        pass

    return ''


commit_msg_filepath = sys.argv[1]
branch = resolve_branch_name()
branch_file_path = '.git/ninja.json'

if not branch:
    sys.exit(0)

with open(branch_file_path, 'r', encoding='utf8') as fp:
  try:
    branch_data = json.load(fp)['data']
    branch_data = [b for b in branch_data if b['branch'].strip() == branch]
    if branch_data:
      branch_data = branch_data[0]

      if 'team' in branch_data:
        team_id = branch_data['team'].split('/')[-1:][0]
      else:
        team_id = ''

      format_msg = ''
      with open(commit_msg_filepath, 'r+') as fh:
        commit_msg = fh.read()
        if '\nTeam: ' not in commit_msg:
          msgs = commit_msg.split(':')
          fh.seek(0, 0)
          if 'team' in branch_data:
            format_msg = '%s(%s): %s\n%s\nTeam: %s' % (msgs[0], team_id, msgs[1], branch_data['title'], branch_data['team'])
          else:
            format_msg = '%s: %s\n%s' % (msgs[0], msgs[1], branch_data['title'])
          fh.write(format_msg)
        else:
          format_msg = commit_msg
        for line in format_msg.split('\n'):
          if len(line) > 0 and line[0] != '#':
            print('\033[0;37;42m%s\033[0m' % (line))
  except Exception as e:
    print(e)
    print("\033[0;37;41m 提交信息格式化失败！ \033[0m")
