#!/usr/bin/env python
# coding=UTF-8
import sys, re, json
from subprocess import check_output

commit_msg_filepath = sys.argv[1]
branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip().decode('UTF-8')

branch_file_path = '.git/ninja.json'

with open(branch_file_path, 'r', encoding='utf8') as fp:
  try:
    branch_data = json.load(fp)['data']
    branch_data = [b for b in branch_data if b['branch'].strip() == branch]
    if branch_data:
      branch_data = branch_data[0]

      if 'scope' in branch_data:
         scope = branch_data['scope']
      elif 'task' in branch_data:
        scope = branch_data['task'].split('/')[-1:][0]
      else:
        scope = ''

      format_msg = ''
      with open(commit_msg_filepath, 'r+') as fh:
        commit_msg = fh.read()
        if '\nTask: ' not in commit_msg:
          msgs = commit_msg.split(':')
          fh.seek(0, 0)
          if scope:
            format_msg = '%s(%s): %s\n%s\nTask: %s' % (msgs[0], scope, msgs[1], branch_data['title'], branch_data['task'])
          else:
            format_msg = '%s: %s\n%s' % (msgs[0], msgs[1], branch_data['title'])
          fh.write(format_msg)
        else:
          format_msg = commit_msg
        for line in format_msg.split('\n'):
          if len(line) > 0 and line[0] != '#':
            print('\033[0;37;42m%s\033[0m' % (line))
  except Exception as e:
    print(e)
    print("\033[0;37;41m 提交信息格式化失败！ \033[0m")
